package com.cardsync.domain.exception;

public enum ErrorCode {
  BUSINESS_ERROR("error.business"),
  VALIDATION_ERROR("error.validation"),
  INTERNAL_ERROR("error.internal"),
  NOT_FOUND("error.NOT_FOUND"),
  ACCESS_DENIED("error.ACCESS_DENIED"),
  SESSION_EXPIRED("error.SESSION_EXPIRED"),

  COMPANY_NOT_FOUND("error.COMPANY_NOT_FOUND"),
  ACQUIRER_NOT_FOUND("error.ACQUIRER_NOT_FOUND"),
  CONTRACT_NOT_FOUND("error.CONTRACT_NOT_FOUND"),

  ESTABLISHMENT_NOT_FOUND("error.ESTABLISHMENT_NOT_FOUND"),
  ESTABLISHMENT_DELETE_IN_USE("error.ESTABLISHMENT_DELETE_IN_USE"),
  ESTABLISHMENT_ALREADY_EXISTS("error.ESTABLISHMENT_ALREADY_EXISTS"),

  USER_NOT_FOUND("error.USER_NOT_FOUND"),
  USER_DOCUMENT_ALREADY_EXISTS("error.USER_DOCUMENT_ALREADY_EXISTS"),
  USER_USERNAME_ALREADY_EXISTS("error.USER_USERNAME_ALREADY_EXISTS"),

  USER_UPDATE_SUPPORT_NOT_ALLOWED("error.USER_UPDATE_SUPPORT_NOT_ALLOWED"),
  USER_ACTIVATE_SUPPORT_NOT_ALLOWED("error.USER_ACTIVATE_SUPPORT_NOT_ALLOWED"),
  USER_DEACTIVATE_SUPPORT_NOT_ALLOWED("error.USER_DEACTIVATE_SUPPORT_NOT_ALLOWED"),

  USER_ACTIVATE_INVALID_STATUS("error.USER_ACTIVATE_INVALID_STATUS"),
  USER_ACTIVATE_PROTECTED_NOT_ALLOWED("error.USER_ACTIVATE_PROTECTED_NOT_ALLOWED"),
  USER_DEACTIVATE_SELF_NOT_ALLOWED("error.USER_DEACTIVATE_SELF_NOT_ALLOWED"),
  USER_DEACTIVATE_PROTECTED_NOT_ALLOWED("error.USER_DEACTIVATE_PROTECTED_NOT_ALLOWED"),
  USER_DEACTIVATE_INVALID_STATUS("error.USER_DEACTIVATE_INVALID_STATUS"),
  USER_BULK_IDS_REQUIRED("error.USER_BULK_IDS_REQUIRED"),

  INVITE_RESEND_NOT_ALLOWED("error.INVITE_RESEND_NOT_ALLOWED"),
  INVITE_RESEND_USER_INACTIVE("error.INVITE_RESEND_USER_INACTIVE"),
  INVITE_RESEND_USER_ALREADY_ACTIVE("error.INVITE_RESEND_USER_ALREADY_ACTIVE"),

  GROUP_REQUIRED("error.GROUP_REQUIRED"),
  GROUP_NOT_FOUND("error.GROUP_NOT_FOUND"),
  GROUP_NAME_ALREADY_EXISTS("error.GROUP_NAME_ALREADY_EXISTS"),
  GROUP_DELETE_SUPPORT_NOT_ALLOWED("error.GROUP_DELETE_SUPPORT_NOT_ALLOWED"),
  GROUP_DELETE_IN_USE("error.GROUP_DELETE_IN_USE"),
  PERMISSION_NOT_FOUND("error.PERMISSION_NOT_FOUND"),

  INVALID_EMAIL("error.INVALID_EMAIL"),
  DOCUMENT_REQUIRED("error.DOCUMENT_REQUIRED"),
  NAME_REQUIRED("error.NAME_REQUIRED"),

  EMAIL_NOT_SEND("error.EMAIL_NOT_SEND"),
  EMAIL_AUTHENTICATION_FAILED("error.EMAIL_AUTHENTICATION_FAILED"),

  PASSWORD_CURRENT_INVALID("error.PASSWORD_CURRENT_INVALID"),
  PASSWORD_RESET_RATE_LIMIT_EXCEEDED("error.PASSWORD_RESET_RATE_LIMIT_EXCEEDED"),
  PASSWORD_POLICY_INVALID("error.PASSWORD_POLICY_INVALID");

  private final String messageKey;

  ErrorCode(String messageKey) {
    this.messageKey = messageKey;
  }

  public String code() {
    return name();
  }

  public String messageKey() {
    return messageKey;
  }
}
