package com.cardsync.core.file.util;

import java.util.Map;

/**
 * Tabela IX (Código de ajuste) do manual "Extrato Eletrônico" Cielo v15.15 — 558 códigos,
 * extraídos via pdftotext -raw e cruzados com -layout (que desalinhava 3 blocos da tabela por
 * um deslocamento de linha, mesmo risco documentado em feedback_pdftotext_layout_table_shift_risk).
 *
 * Só detalha o MOTIVO de um lançamento que já é ajuste pela Tabela II (campo "Tipo de
 * lançamento") — não define o tipo em si, e vem em branco pra tipos "01"/"02"/"03"/"42" (e às
 * vezes pra outros tipos também, nesse caso o manual instrui usar só o texto da Tabela II).
 */
public final class CieloAdjustmentReasonCatalog {

  private CieloAdjustmentReasonCatalog() {
  }

  private static final Map<String, String> BY_CODE = Map.ofEntries(
    Map.entry("0000", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0001", "Pagamento/devolução de vendas pendentes de liquidação pela Cielo"),
    Map.entry("0002", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0003", "Outros acertos"),
    Map.entry("0004", "Cobrança de plano Cielo"),
    Map.entry("0005", "Cobrança/devolução referente ao desconto incorreto da taxa administrativa de venda (MDR)"),
    Map.entry("0006", "Outros acertos"),
    Map.entry("0007", "Crédito/débito de valores rejeitados"),
    Map.entry("0008", "Pagamento/devolução para correção de venda efetuada fora do prazo de pagamento"),
    Map.entry("0009", "Pagamento/devolução de crédito temporário disponibilizado em análise de processo financeiro"),
    Map.entry("0010", "Regularização de pagamento de vendas pendentes ao estabelecimento comercial"),
    Map.entry("0011", "Valores não reconhecidos"),
    Map.entry("0012", "Pagamento/devolução de crédito não realizado"),
    Map.entry("0013", "Duplicidade referente Visa cash"),
    Map.entry("0014", "Reenvio de débito não cumprido pelo banco anteriormente"),
    Map.entry("0015", "Pagamento/devolução de crédito agendado ao estabelecimento comercial não vinculado a atividades financeiras"),
    Map.entry("0016", "Negociação com área de prevenção"),
    Map.entry("0017", "Pagamento/devolução de valor não efetuado dentro do prazo de pagamento"),
    Map.entry("0018", "Pagamento/devolução referente ao cancelamento de antecipação"),
    Map.entry("0019", "Pagamento/devolução de acertos diversos"),
    Map.entry("0020", "Valores não processados"),
    Map.entry("0021", "Crédito/débito de acerto ref. Valor debitado em conta-corrente"),
    Map.entry("0022", "Cobrança/devolução de duplicidade de processamento do vale pedágio"),
    Map.entry("0023", "Reenvio de crédito/débito não cumprido pelo banco"),
    Map.entry("0024", "Pagamento/devolução do serviço de recarga de celular"),
    Map.entry("0025", "Pagamento/devolução de valor não recebido devido a divergência nos dados bancários"),
    Map.entry("0026", "Devolução de valores creditados/debitados indevidamente"),
    Map.entry("0027", "Crédito/débito de transação eléctron não processada"),
    Map.entry("0028", "Ajuste a Crédito/débito para antecipação/repasse"),
    Map.entry("0029", "Regularização de pagamento de vendas pendentes ao estabelecimento comercial"),
    Map.entry("0030", "Ajuste transação crediário/construcard"),
    Map.entry("0031", "Cobrança/devolução de dívida negociada com o estabelecimento comercial"),
    Map.entry("0032", "Estorno de débito/crédito ref. a acerto de duplicidade de crédito"),
    Map.entry("0033", "Pagamento antecipação"),
    Map.entry("0034", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0035", "Regularização de pagamento de antecipação de recebíveis pré-07/06/2021"),
    Map.entry("0036", "Crédito/débito de transação eléctron real não processada"),
    Map.entry("0037", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0038", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0039", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0040", "Reprocessamento transação eléctron"),
    Map.entry("0041", "Transação agronegócio-custeio"),
    Map.entry("0042", "Cobrança/devolução do produto de financiamento Agro Custeio - Banco do Brasil"),
    Map.entry("0043", "Crédito/débito de venda com cartão de débito Bradesco"),
    Map.entry("0044", "Crédito/débito cessão de direito agenda a vista"),
    Map.entry("0045", "Crédito/débito de transação eléctron"),
    Map.entry("0046", "Cobrança/devolução de venda não processada"),
    Map.entry("0047", "Regularização de pagamento de vendas pendentes ao estabelecimento comercial"),
    Map.entry("0048", "Reenvio de antecipação rejeitada"),
    Map.entry("0049", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0050", "Estorno de reversão pagamento duplicidade - ARV"),
    Map.entry("0051", "Premiação Visa"),
    Map.entry("0052", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0053", "Troco fácil"),
    Map.entry("0054", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0055", "Webservice boleto"),
    Map.entry("0056", "Crédito referente parcelas antecipadas (pré-balcão)"),
    Map.entry("0057", "Reembolso de CMPF"),
    Map.entry("0058", "Crédito/débito ref. parcelas antecipadas"),
    Map.entry("0059", "Cobrança/devolução da tarifa do extrato papel"),
    Map.entry("0060", "Cobrança/devolução de mensalidade retroativa de aluguel da máquina Cielo"),
    Map.entry("0061", "Cobrança diferença de plano Cielo"),
    Map.entry("0062", "Plano Cielo – Pin Pads"),
    Map.entry("0063", "Cobrança/devolução da mensalidade do aluguel da máquina Cielo"),
    Map.entry("0064", "Débito venda autorização negada"),
    Map.entry("0065", "Cobrança/devolução da mensalidade do aluguel da máquina Cielo"),
    Map.entry("0066", "Plano Cielo - correspondente bancário"),
    Map.entry("0067", "Plano Cielo - TEF discado"),
    Map.entry("0068", "Desconto plano Cielo - cobrança direta"),
    Map.entry("0069", "Plano Cielo - TEF IP"),
    Map.entry("0070", "Desconto comercial sobre taxa"),
    Map.entry("0071", "Cobrança/devolução da tarifa de cadastro"),
    Map.entry("0072", "Aluguel de equipamento"),
    Map.entry("0073", "Tarifa de cadastro"),
    Map.entry("0074", "Crédito/débito promoção paixão por futebol Visa"),
    Map.entry("0075", "Crédito/débito concessionaria"),
    Map.entry("0076", "Crédito/débito arrecadador"),
    Map.entry("0077", "Crédito/débito emissor"),
    Map.entry("0078", "Tarifa de consulta transação AVS"),
    Map.entry("0079", "Repasse de tarifa transação AVS"),
    Map.entry("0080", "Crédito/débito cessão de recebíveis de venda parcelada"),
    Map.entry("0081", "Crédito/débito de tarifa ref. Envio de bobina"),
    Map.entry("0082", "Crédito/débito de tarifa ref. Envio de extrato papel"),
    Map.entry("0083", "Crédito/débito de tarifa ref. Visita de manutenção POS"),
    Map.entry("0084", "Ajuste a crédito/débito transação Flex Car"),
    Map.entry("0085", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0086", "Créditos diversos Flex Car"),
    Map.entry("0087", "Débitos diversos Flex Car"),
    Map.entry("0088", "Webservice antifraude sem BPO"),
    Map.entry("0089", "Webservice antifraude com BPO"),
    Map.entry("0090", "Estorno/reprocessamento transação eléctron troco fácil"),
    Map.entry("0091", "Transação saque troco fácil"),
    Map.entry("0092", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0093", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0094", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0095", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0096", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0097", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0098", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0099", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0100", "Estorno cancelamento de venda via terminal parcelado loja"),
    Map.entry("0101", "Crédito/débito ref. A erro no cadastramento da moeda"),
    Map.entry("0102", "Regularização de pagamento de vendas pendentes ao estabelecimento comercial"),
    Map.entry("0103", "Crédito/débito de valores complementares"),
    Map.entry("0104", "Cobrança/estorno de aluguel de terminais eletrônicos"),
    Map.entry("0105", "Crédito/débito de taxa de comissão"),
    Map.entry("0106", "Crédito/débito referente a valores contestados pelo portador através do banco emissor"),
    Map.entry("0107", "Débito/crédito por pagamentos de valores rejeitados Visa cash"),
    Map.entry("0108", "Correção monetária"),
    Map.entry("0109", "Crédito/débito temporário - processo em análise"),
    Map.entry("0110", "Valores não processados"),
    Map.entry("0111", "Valores não reconhecidos"),
    Map.entry("0112", "Crédito/débito ref. A pagamento em conta-corrente divergente"),
    Map.entry("0113", "Outros acertos"),
    Map.entry("0114", "Débito/estorno não cumprido"),
    Map.entry("0115", "Pagamento/devolução de valor por acordo jurídico"),
    Map.entry("0116", "Tarifa/estorno 2 via extrato papel"),
    Map.entry("0117", "Reenvio de Crédito/estorno não cumprido pelo bco - ARV"),
    Map.entry("0118", "Estorno de débito referente à vendas Cielo Promo"),
    Map.entry("0119", "Acertos diversos"),
    Map.entry("0120", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0121", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0125", "Crédito/débito referente produto seguro"),
    Map.entry("0126", "Webservice recorrência inteligente"),
    Map.entry("0127", "Crédito/débito referente a valores contestados pelo portador através do banco emissor"),
    Map.entry("0128", "Crédito/débito referente a valores contestados pelo portador através do banco emissor"),
    Map.entry("0129", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0130", "Webservice pacote"),
    Map.entry("0131", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0132", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0133", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0134", "Acerto de recarga dinheiro e parceiros para o M4U"),
    Map.entry("0135", "Cessão de direitos"),
    Map.entry("0136", "Estorno/reenvio de débito não cumprido"),
    Map.entry("0137", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0138", "Webservice boleto"),
    Map.entry("0139", "Cobrança/devolução referente ao plano Cielo Controle"),
    Map.entry("0140", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0141", "Outros acertos"),
    Map.entry("0142", "Transferência de valores entre estabelecimentos da mesma raiz de CNPJ para compensação de saldo"),
    Map.entry("0143", "Crédito/débito agro custeio"),
    Map.entry("0144", "Cobrança/devolução referente ao plano Cielo Controle"),
    Map.entry("0145", "Transferência de valores do dev. banco"),
    Map.entry("0149", "Cobrança/devolução de parcela do Receba Mais"),
    Map.entry("0150", "Cobrança/devolução da tarifa de aquisição de recebíveis via central de atendimento"),
    Map.entry("0151", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0152", "Transação não processada"),
    Map.entry("0153", "Pagamento/devolução sobre acordo jurídico"),
    Map.entry("0154", "Confiança Cielo"),
    Map.entry("0155", "Contrato de caução"),
    Map.entry("0156", "Cobrança de multa da bandeira Mastercard por excesso de vendas contestadas"),
    Map.entry("0157", "Cobrança/devolução de aluguel por não atingimento de meta de faturamento (Cielo Livre)"),
    Map.entry("0158", "Pagamento/devolução de comissão periódica"),
    Map.entry("0159", "Pagamento/devolução de comissão periódica"),
    Map.entry("0160", "Cobrança de mensalidade de aluguel da máquina Cielo"),
    Map.entry("0161", "Cobrança/estorno aluguel de terminais eletrônicos para férias e eventos"),
    Map.entry("0162", "Cobrança/estorno aluguel de terminais eletrônicos C.C.C."),
    Map.entry("0163", "Cobrança/estorno aluguel de terminais eletrônicos C.S.C."),
    Map.entry("0164", "Cobrança/estorno aluguel de terminais eletrônicos (leitor de trilha)"),
    Map.entry("0165", "Cobrança/estorno aluguel de terminais eletrônicos"),
    Map.entry("0166", "Cobrança indevida"),
    Map.entry("0167", "Pagamento/devolução de comissão periódica"),
    Map.entry("0168", "Pagamento/devolução de comissão periódica"),
    Map.entry("0169", "POS incentivado"),
    Map.entry("0170", "Estorno/desconto comercial sobre taxa de desconto"),
    Map.entry("0171", "Desconto comercial sobre taxa de desconto eléctron"),
    Map.entry("0172", "Desconto comercial sobre taxa desconto - parcelado"),
    Map.entry("0173", "Pagamento de incentivo emissores faturamento eléctron"),
    Map.entry("0174", "Repasse de multa de bandeira por não conformidade"),
    Map.entry("0175", "Cobrança/devolução de taxa do receba rápido"),
    Map.entry("0176", "Ação promocional de Cashback"),
    Map.entry("0177", "Transferência de valores entre estabelecimentos da mesma raiz de CNPJ para compensação de saldo"),
    Map.entry("0178", "Fullcommerce - Velocity"),
    Map.entry("0179", "Reprocessamento transação carnê"),
    Map.entry("0180", "Fullcommerce - conciliador"),
    Map.entry("0181", "Antifraude automático"),
    Map.entry("0182", "Antifraude Advanced"),
    Map.entry("0183", "Fullcommerce cartão protegido"),
    Map.entry("0184", "Fullcommerce - gateway"),
    Map.entry("0185", "Antifraude - manual"),
    Map.entry("0186", "Antifraude Enterprise"),
    Map.entry("0188", "Cobrança fee Copuneria"),
    Map.entry("0189", "Crédito/débito Copuneria"),
    Map.entry("0190", "Compensação de valores pendentes"),
    Map.entry("0191", "Crédito/débito receba mais enviado c/c"),
    Map.entry("0192", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0193", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0194", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0195", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0196", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0197", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0198", "Receba rápido compensação entre estabelecimentos"),
    Map.entry("0199", "Crédito/débito desenvolvedor Cielo lio"),
    Map.entry("0200", "Desconto negociação"),
    Map.entry("0201", "Cessão de direito eléctron pré-datado"),
    Map.entry("0202", "Crédito/débito aceleração de Cessão de direito eléctron pré-datado"),
    Map.entry("0203", "Antecipação de cessão"),
    Map.entry("0204", "Transação carnê Bradesco"),
    Map.entry("0205", "Reprocessamento transação carnê"),
    Map.entry("0206", "Estorno cancelamento venda carnê"),
    Map.entry("0207", "Cancelamento venda carnê"),
    Map.entry("0208", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0209", "Pagamento/devolução de comissão periódica"),
    Map.entry("0210", "Pagamento/devolução de comissão periódica"),
    Map.entry("0211", "Pagamento/devolução de comissão periódica"),
    Map.entry("0212", "Pagamento/devolução de comissão periódica"),
    Map.entry("0213", "Pagamento/devolução de comissão periódica"),
    Map.entry("0214", "Pagamento/devolução de comissão periódica"),
    Map.entry("0215", "Pagamento/devolução de comissão periódica"),
    Map.entry("0216", "Ajuste periódico de comissão"),
    Map.entry("0217", "Ajuste periódico de comissão"),
    Map.entry("0218", "Ajuste periódico de comissão"),
    Map.entry("0219", "Anistia dívidas cliente varejo"),
    Map.entry("0220", "Venda cancelada pelo estabelecimento comercial"),
    Map.entry("0222", "Reembolso EC PP"),
    Map.entry("0224", "Compensação entre bandeiras online"),
    Map.entry("0225", "Painel meu negócio"),
    Map.entry("0238", "Reenvio débito não cumprido pelo banco anteriormente"),
    Map.entry("0246", "Crédito/débito referente a Velocity Check"),
    Map.entry("0251", "Cobrança/devolução de multa da bandeira por excesso de retentativas de venda no mesmo cartão"),
    Map.entry("0252", "Pagamento/devolução de valor efetuado via TED"),
    Map.entry("0253", "Pagamento/devolução de valor efetuado via PIX"),
    Map.entry("0254", "Tarifa da bandeira"),
    Map.entry("0255", "Reembolso/cobrança transação garantida"),
    Map.entry("0256", "Cobrança/devolução de taxa por pagamento efetuado via PIX"),
    Map.entry("0257", "Cobrança/pagamento para regularizar operações de vendas PIX em agenda financeira"),
    Map.entry("0258", "Cobrança/devolução de tarifa da bandeira por vendas contestadas"),
    Map.entry("0259", "Divergência do valor da nota fiscal - compra de máquina"),
    Map.entry("0260", "Outros acertos"),
    Map.entry("0261", "Parceria eleve"),
    Map.entry("0262", "Estorno boleto comodato Cielo"),
    Map.entry("0264", "Cobrança/devolução da compra de máquina Cielo sem aluguel"),
    Map.entry("0265", "Pagamento/devolução para correção de estorno indevido"),
    Map.entry("0267", "Pagamento/devolução de estorno indevido"),
    Map.entry("0269", "Pagamento/devolução para regularizar o processamento de parcelas pendentes"),
    Map.entry("0270", "Pagamento/devolução de valor em aberto decorrente da antecipação de recebíveis"),
    Map.entry("0271", "Outros acertos"),
    Map.entry("0272", "Cobrança de pagamento indevido e/ou devolução de cobrança indevida relacionados ao saldo utilizado em negociações de recebíveis"),
    Map.entry("0273", "Outros acertos"),
    Map.entry("0274", "Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial"),
    Map.entry("0275", "Ressarcimento de terminais_ recuperação de ativos"),
    Map.entry("0276", "Outros acertos"),
    Map.entry("0277", "Acerto ref. ao cancel/estorno do pedido de venda máquina"),
    Map.entry("0278", "Outros acertos"),
    Map.entry("0279", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0280", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0281", "Regularização de terminais não recuperados"),
    Map.entry("0282", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0283", "Compensação de créditos/débitos"),
    Map.entry("0284", "Compensação de crédito/débito na conta digital"),
    Map.entry("0285", "Outros acertos"),
    Map.entry("0286", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento"),
    Map.entry("0287", "Ajuste de aluguel equipamentos inativos"),
    Map.entry("0288", "Venda contestada pelo portador do cartão através do banco emissor"),
    Map.entry("0289", "De/para número logico"),
    Map.entry("0290", "Outros acertos"),
    Map.entry("0291", "Cobrança/devolução de pagamento indevido ao estabelecimento comercial"),
    Map.entry("0292", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0293", "Ajuste débito/crédito Facebook"),
    Map.entry("0294", "Ajuste reembolso Facebook"),
    Map.entry("0295", "Ajuste reembolso Facebook"),
    Map.entry("0296", "Crédito voucher - Facebook Donation"),
    Map.entry("0297", "Cobrança/devolução do valor da máquina que não foi devolvida pelo estabelecimento comercial"),
    Map.entry("0298", "Cobrança/devolução de pagamento indevido ao estabelecimento comercial"),
    Map.entry("0299", "Cobrança/devolução de multa por inconformidade com as regras da bandeira"),
    Map.entry("0300", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0301", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0302", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0303", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0304", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0305", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0306", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0307", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0308", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0309", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0310", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0311", "Transação acima do limite sem código de autorização"),
    Map.entry("0312", "Transação em duplicidade"),
    Map.entry("0313", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0314", "Transação com número do cartão inexistente"),
    Map.entry("0315", "Cobrança/devolução decorrente do intercâmbio sobre vendas"),
    Map.entry("0316", "Transação com número do cartão inexistente"),
    Map.entry("0317", "Estorno de débito efetuado em transação realizada com chip"),
    Map.entry("0318", "Estorno de débito efetuado em transação realizado com chip"),
    Map.entry("0320", "Tarifa/estorno de multa programa monitoria chargeback"),
    Map.entry("0321", "Transação acima do limite sem código de autorização"),
    Map.entry("0322", "Venda em duplicidade"),
    Map.entry("0323", "Crédito por envio do comprovante"),
    Map.entry("0324", "Pagamento/devolução de valor pré-negociado com o estabelecimento à vista"),
    Map.entry("0325", "Outros acertos"),
    Map.entry("0326", "Venda desmembrada em mais de um comprovante"),
    Map.entry("0327", "Assinatura divergente - portador não efetuou compra"),
    Map.entry("0328", "Pré-arbitragem/pré-compliance"),
    Map.entry("0329", "Pré-arbitragem/pré-compliance negociados parcelado"),
    Map.entry("0330", "Cobrança/devolução de multa do programa monitoria das bandeiras"),
    Map.entry("0331", "Transação acima do limite sem código de autorização"),
    Map.entry("0332", "Venda em duplicidade não comprovada"),
    Map.entry("0333", "Envio do comprovante pelo estabelecimento"),
    Map.entry("0334", "Venda com número de cartão existente"),
    Map.entry("0335", "Crédito/débito referente análise de intercambio"),
    Map.entry("0336", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0337", "Processos de mediação"),
    Map.entry("0338", "Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial"),
    Map.entry("0339", "Cobrança/devolução de cancelamento que não foi efetuado na data da venda"),
    Map.entry("0340", "Pagamento/devolução para correção relacionados a cancelamentos de vendas"),
    Map.entry("0341", "Outros acertos"),
    Map.entry("0342", "Pagamento/devolução de comissão periódica"),
    Map.entry("0343", "Cobrança/devolução de valores pagos em confiança"),
    Map.entry("0344", "Cobrança/devolução referente à contestação de débito em conta efetuado pelo banco"),
    Map.entry("0345", "Cobrança/devolução do serviço Renova Fácil/ ABU Mastercard"),
    Map.entry("0346", "Cobrança/devolução referente a venda cancelada que foi paga ao estabelecimento comercial"),
    Map.entry("0347", "Cobrança/devolução de venda indevidamente paga ao estabelecimento comercial em antecipações/garantias"),
    Map.entry("0348", "Cobrança/devolução de multa do programa monitoria das bandeiras"),
    Map.entry("0349", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0350", "Estabelecimento Special Handling"),
    Map.entry("0351", "Venda com código de autorização"),
    Map.entry("0352", "Contestação da negociação de recebíveis"),
    Map.entry("0353", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0354", "Acerto de débito em duplicidade"),
    Map.entry("0356", "Portador não reconhece valor parcial da venda."),
    Map.entry("0357", "Intercambio referente a contestação do portador"),
    Map.entry("0358", "Venda contestada pelo banco a pedido do portador do cartão"),
    Map.entry("0359", "Irregularidade na transação"),
    Map.entry("0360", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0361", "Chargeback transação débito - bandeira elo"),
    Map.entry("0362", "Chargeback transação parcelado - bandeira elo"),
    Map.entry("0363", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0364", "Devolução de cobrança contestada da bandeira Elo pelo estabelecimento comercial"),
    Map.entry("0365", "Intercambio ref. contestação do portado"),
    Map.entry("0366", "Análise de intercambio"),
    Map.entry("0367", "Envio do comprovante pelo estabelecimento"),
    Map.entry("0368", "Transação apresentada dentro do prazo contratual (intercambio)"),
    Map.entry("0369", "Envio do comprovante pelo estabelecimento"),
    Map.entry("0370", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0371", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0372", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0373", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0374", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0375", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0376", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0377", "Venda contestada pelo portador através do banco emissor ou Reversão de cobrança de venda contestada pelo portador através do banco emissor"),
    Map.entry("0378", "Pagamento/devolução de débito duplicado na conta do estabelecimento comercial"),
    Map.entry("0379", "Cobrança/devolução para corrigir vendas antecipadas duplicadas"),
    Map.entry("0380", "Crédito/débito crediário Visa"),
    Map.entry("0381", "Cobrança/devolução para regularização de recebíveis de outras adquirentes antecipados com a Cielo"),
    Map.entry("0382", "Correção de crédito indevido para CPF/CNPJ"),
    Map.entry("0383", "Correção de venda cobrada indevidamente do estabelecimento comercial em antecipações/garantias"),
    Map.entry("0384", "Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial"),
    Map.entry("0385", "Outros acertos"),
    Map.entry("0386", "Pagamento/devolução para abater divergência entre valor devido e liquidado"),
    Map.entry("0387", "Cobrança/devolução de pagamento indevido ao estabelecimento comercial"),
    Map.entry("0388", "Ajuste referente ordem de pagamento"),
    Map.entry("0389", "Crédito/débito referente a reversão de débito por cartão inexistente"),
    Map.entry("0391", "Regularização de pagamento de vendas pendentes ao estabelecimento comercial"),
    Map.entry("0392", "Outros acertos"),
    Map.entry("0393", "Regularização de pagamento de vendas pendentes ao estabelecimento comercial"),
    Map.entry("0394", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0396", "Crédito/débito devido a erro de sistema"),
    Map.entry("0397", "Erro no processamento da venda"),
    Map.entry("0399", "Ajuste a Crédito/débito por comprovante de venda legível/ilegível"),
    Map.entry("0400", "Copia não atendida"),
    Map.entry("0401", "Copia ilegível"),
    Map.entry("0402", "Copia incorreta"),
    Map.entry("0403", "Envio de documentos comprobatórios da venda"),
    Map.entry("0404", "Outros acertos"),
    Map.entry("0408", "Outros acertos"),
    Map.entry("0409", "Crédito/débito transações parceladas negociadas com a Visanet"),
    Map.entry("0410", "Valores negociados"),
    Map.entry("0411", "Cashback - aluguel"),
    Map.entry("0412", "Pagamento/devolução de cashback previsto na agenda financeira"),
    Map.entry("0413", "Cobrança sobre venda paga a maior/em duplicidade ao estabelecimento comercial"),
    Map.entry("0414", "Cobrança/devolução de pagamento indevido na conta do estabelecimento comercial por ocorrência sistêmica"),
    Map.entry("0415", "Cobrança/devolução de vendas pagas em duplicidade e/ou valor maior ao estabelecimento comercial"),
    Map.entry("0416", "Ajuste de vendas indevidas Amex, Hiper e JCB"),
    Map.entry("0417", "Ajuste de vendas indevidas Amex, Hiper e JCB"),
    Map.entry("0418", "Outros acertos"),
    Map.entry("0419", "Outros acertos"),
    Map.entry("0421", "Planos e serviços e-commerce"),
    Map.entry("0422", "Planos e serviços e-commerce"),
    Map.entry("0423", "Planos e serviços e-commerce"),
    Map.entry("0424", "Cobrança/devolução do serviço de cartão protegido"),
    Map.entry("0425", "Cobrança/devolução do serviço consulta Bin"),
    Map.entry("0426", "Cobrança/devolução do serviço de verificação de cartão"),
    Map.entry("0427", "Outros acertos"),
    Map.entry("0428", "Devolução de cessão indevida"),
    Map.entry("0429", "Cobrança/devolução de recebimento de operação com prejuízo financeiro"),
    Map.entry("0430", "Cobrança/devolução do serviço de retentativas de vendas Cielo"),
    Map.entry("0431", "Pagamento/devolução da campanha acesse e ganhe"),
    Map.entry("0432", "Cobrança/devolução da mensalidade do Cielo Conciliador"),
    Map.entry("0434", "Outros acertos"),
    Map.entry("0435", "Pagamento/devolução referente ao incentivo de antecipação"),
    Map.entry("0436", "Pagamento/devolução de crédito da campanha faturou e ganhou - cashback"),
    Map.entry("0437", "Pagamento/devolução de cashback da campanha vendeu, ganhou"),
    Map.entry("0439", "Cobrança/devolução de tarifa da bandeira por vendas não processadas"),
    Map.entry("0440", "Cobrança/Devolução de interchange plus"),
    Map.entry("0441", "Cobrança/devolução de pagamento indevido na conta do estabelecimento comercial por ocorrência sistêmica"),
    Map.entry("0442", "Pagamento/devolução de valores de vendas devido ao estabelecimento comercial, em decorrência do status de inconformidade com as regras da bandeira"),
    Map.entry("0443", "Ressarcimento de correção monetária sobre pagamentos das vendas fora do prazo"),
    Map.entry("0445", "Cobrança sobre saldo reestabelecido ao estabelecimento comercial na conta de pagamento do Banco do Brasil"),
    Map.entry("0446", "Cobrança de venda paga em duplicidade ao estabelecimento comercial por ocorrência sistêmica"),
    Map.entry("0447", "Cobrança sobre saldo reestabelecido ao estabelecimento comercial na conta de pagamento do Banco Bradesco"),
    Map.entry("0448", "Cobrança/devolução para regularização de recebíveis de outras adquirentes antecipados com a Cielo"),
    Map.entry("0449", "Pagamento/devolução de valor indevido na conta do estabelecimento comercial por ocorrência sistêmica"),
    Map.entry("0450", "Cobrança/devolução de multa por atraso no pagamento com a Cielo"),
    Map.entry("0452", "Crédito/débito referente a valores contestados pelo portador através do banco emissor"),
    Map.entry("0453", "Crédito/débito referente a valores contestados pelo portador através do banco emissor"),
    Map.entry("0454", "Crédito/débito referente a valores contestados pelo portador através do banco emissor"),
    Map.entry("0459", "Ressarcimento de correção monetária sobre pagamentos das vendas fora do prazo"),
    Map.entry("0460", "Cobrança para regularização de valores em aberto do estabelecimento com a Cielo no Banco do Brasil"),
    Map.entry("0461", "Ressarcimento de correção monetária sobre pagamentos das vendas fora do prazo"),
    Map.entry("0462", "Cobrança para regularização de valores em aberto do estabelecimento com a Cielo no Banco Bradesco"),
    Map.entry("0463", "Cobrança/devolução consumo do serviço renova fácil"),
    Map.entry("0464", "Cobrança/devolução da mensalidade do aluguel da máquina Cielo"),
    Map.entry("0465", "Estorno/Cobrança de aluguel de máquinas excedentes"),
    Map.entry("0467", "Repasse de cobrança conforme novo programa monitoração (bandeira MasterCard)"),
    Map.entry("0468", "Cashback devido alcance de meta de faturamento de máquinas em Cielo Facilita"),
    Map.entry("0469", "Repasse/Devolução da tarifa de não tokenização Visa"),
    Map.entry("0470", "Devolução da mensalidade do aluguel da máquina Cielo"),
    Map.entry("0471", "Devolução da compra de máquina Cielo sem aluguel"),
    Map.entry("0473", "Cobrança/devolução de serviço mastercard global wholesale"),
    Map.entry("0482", "Cobrança/devolução do programa PCI DSS sobre segurança dos dados dos cartões em transações"),
    Map.entry("0484", "Cobrança/devolução de serviço cross border"),
    Map.entry("0485", "Taxa de tentativa de liquidação"),
    Map.entry("0486", "Cobrança/devolução tarifa da bandeira por cadastro/renovação de provedor de serviços"),
    Map.entry("0488", "Cobrança/devolução de tarifa da bandeira por arbitragem em vendas contestadas"),
    Map.entry("0508", "Juros e correção monetária"),
    Map.entry("0510", "Valores não processados"),
    Map.entry("0512", "Pagamento em conta-corrente divergente"),
    Map.entry("0515", "Acordo jurídico"),
    Map.entry("0517", "Reenvio de crédito não cumprido pelo banco anteriormente"),
    Map.entry("0521", "Estorno/débito de reversão de lançamento a débito (baixa forcada)"),
    Map.entry("0522", "Lançamento a crédito baixa forcada"),
    Map.entry("0523", "Transferência de valores entre estabelecimentos da mesma raiz de CNPJ para compensação de saldo"),
    Map.entry("0524", "Devolução de lançamento de venda para ajustar o saldo em uma nova data"),
    Map.entry("0528", "Acerto de cobrança"),
    Map.entry("0529", "Pagamento de incentivo ao EC"),
    Map.entry("0530", "Acerto autorizado pela Cielo"),
    Map.entry("0540", "Estorno de reversão de crédito"),
    Map.entry("0541", "Cobrança/devolução para correção de débito indevido ao estabelecimento comercial"),
    Map.entry("0542", "Cobrança/devolução de dívida negociada com o estabelecimento comercial"),
    Map.entry("0548", "Valores pendentes"),
    Map.entry("0549", "Reversão de aluguel de POS"),
    Map.entry("0550", "Valores suspensos"),
    Map.entry("0558", "Acerto por tarifa anteriormente cancelada"),
    Map.entry("0560", "Acerto referente a acordo comercial"),
    Map.entry("0601", "Acerto de valores não processados"),
    Map.entry("0602", "Acerto referente a regularização de data de pagamento"),
    Map.entry("0603", "Acerto de valores complementares"),
    Map.entry("0604", "Acerto de taxa de comissão"),
    Map.entry("0605", "Crédito/débito referente a valores contestados"),
    Map.entry("0606", "Correção monetária"),
    Map.entry("0607", "Débito/estorno de débito de valores não reconhecidos"),
    Map.entry("0608", "Crédito/débito referente a pagamento em conta-corrente divergente"),
    Map.entry("0609", "Reenvio de crédito não cumprido pelo banco anteriormente"),
    Map.entry("0610", "Acerto de valores não processados"),
    Map.entry("0611", "Acerto referente acerto de duplicidade"),
    Map.entry("0613", "Estorno cancelamento de venda Alelo refeição"),
    Map.entry("0614", "Crédito/débito de transação Alelo refeição não processada"),
    Map.entry("0615", "Reenvio de antecipação rejeitada (pré-balcão)"),
    Map.entry("0616", "Acerto referente a negociação com a área de prevenção"),
    Map.entry("0617", "Tarifa operacional sobre créditos Alelo"),
    Map.entry("0618", "POS incentivado"),
    Map.entry("0619", "Acertos diversos"),
    Map.entry("0620", "Estorno/tarifa operacional sobre créditos Alelo"),
    Map.entry("0621", "Cancelamento de vendas (envio eletrônico)"),
    Map.entry("0622", "Alelo desenvolvedores"),
    Map.entry("0623", "Reversão de lançamento a Crédito/débito baixado manual"),
    Map.entry("0624", "Reenvio tarifa TOR"),
    Map.entry("0625", "Reenvio tarifa de manutenção Alelo"),
    Map.entry("0626", "Estorno/cobrança de tarifa de cadastro Alelo"),
    Map.entry("0627", "Tarifa mensal - Alelo na medida"),
    Map.entry("0628", "Tarifa mensal - Alelo na medida"),
    Map.entry("0629", "Crédito/débito de antecipação rejeitada"),
    Map.entry("0631", "Estorno/reversão de lançamento a débito baixado manual"),
    Map.entry("0632", "Reversão de lançamento a Crédito/débito baixado manualmente"),
    Map.entry("0633", "Acerto ref. acerto de cobrança"),
    Map.entry("0634", "Estorno/cobrança de débito de acordo de cobrança"),
    Map.entry("0635", "Ajuste a Crédito/débito de valores pendentes"),
    Map.entry("0636", "Crédito/débito referente a acerto de valores suspensos"),
    Map.entry("0637", "Crédito/débito assinatura internet delivery Alelo"),
    Map.entry("0638", "Crédito/débito referente a análise de intercambio cartão cultura"),
    Map.entry("0640", "Outros acertos"),
    Map.entry("0641", "Acerto a débito/crédito referente a negociação com área de prevenção"),
    Map.entry("0645", "Acerto do bloqueio de valor por ordem judicial"),
    Map.entry("0648", "Regularização de pagamento de vendas com status suspenso ao estabelecimento comercial"),
    Map.entry("0649", "Programa Smiles"),
    Map.entry("0650", "Crédito/estorno Smiles referente ao acúmulo de milhas"),
    Map.entry("0651", "Crédito/estorno ao EC referente as milhas Smiles resgatadas"),
    Map.entry("0652", "Programa Smiles"),
    Map.entry("0653", "Pagamento/devolução de transação realizada via boleto bancário"),
    Map.entry("0661", "Crédito/débito referente análise de intercambio refeição"),
    Map.entry("0680", "Cobrança mensal e-lynx"),
    Map.entry("0700", "Cobrança/devolução de venda contestada pelo portador através do banco emissor"),
    Map.entry("0713", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0714", "Crédito/débito de transação Alelo alimentação não processadas"),
    Map.entry("0715", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0716", "Transação Alelo não processada"),
    Map.entry("0720", "Outros acertos"),
    Map.entry("0722", "Pagamento/devolução de venda"),
    Map.entry("0745", "Acerto Hipercard festa de são João"),
    Map.entry("0759", "Cobrança Meliuz"),
    Map.entry("0760", "Estorno Cobrança Meliuz"),
    Map.entry("0761", "Crédito/débito referente a análise de intercambio alimentação"),
    Map.entry("0797", "Cobrança/devolução de valores por compra de aplicativo no Cielo Store"),
    Map.entry("0798", "Cobrança/devolução de valores por compra de aplicativo no Cielo Store"),
    Map.entry("0799", "Cobrança/pagamento de receita sobre aplicativos Cielo Store"),
    Map.entry("0800", "Pagamento/devolução sobre Cielo Store"),
    Map.entry("0810", "Cobrança referente a antecipação de recebíveis"),
    Map.entry("0811", "Serviço conciliador"),
    Map.entry("0812", "Serviço gateway"),
    Map.entry("0813", "Serviço cartão protegido"),
    Map.entry("0814", "Cobrança/devolução do serviço antifraude"),
    Map.entry("0815", "Serviço antifraude"),
    Map.entry("0817", "Acerto cancelamento POS Alelo"),
    Map.entry("0819", "Regularização de valores indevidos"),
    Map.entry("0825", "Cobrança/devolução de tarifa por manutenção cadastral"),
    Map.entry("0879", "Cobrança/devolução do Cielo Controle"),
    Map.entry("0882", "Cobrança/devolução de mensalidade do Farol"),
    Map.entry("0883", "Cobrança/devolução sobre alteração de plano do Farol"),
    Map.entry("0884", "Cobrança/devolução do serviço de Big data"),
    Map.entry("0890", "FCO giro via termina"),
    Map.entry("0891", "Ajuste a crédito transação Capital de giro"),
    Map.entry("0892", "Reversão cancelamento Capital de giro"),
    Map.entry("0893", "Reversão/estorno cancelamento capital de giro via terminal"),
    Map.entry("0894", "Ajuste a Crédito/débito trans. Crédito imobiliário"),
    Map.entry("0895", "Reversão cancelamento crédito imobiliário"),
    Map.entry("0896", "Cancelamento/reversão crédito imobiliário via terminal"),
    Map.entry("0898", "Estorno/ cancelamento de venda produto crédito especializado"),
    Map.entry("0899", "Estorno/ cancelamento de venda produto crédito especializado via terminal"),
    Map.entry("0901", "Acerto Amex indevido"),
    Map.entry("0902", "Tarifa de retentativas Master Card"),
    Map.entry("0910", "Outros acertos"),
    Map.entry("0920", "Comissão emissor internacional"),
    Map.entry("0950", "Crédito/débito referente análise de intercambio refeição"),
    Map.entry("0951", "Débito/crédito referente a análise de intercambio alimentação"),
    Map.entry("0952", "Venda cancelada pelo estabelecimento comercial ou Reversão de cobrança de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0953", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0954", "Pagamento/devolução referente ao incentivo oferecido na conversão dinâmica de moeda (DCC)"),
    Map.entry("0959", "Cobrança/devolução de venda cancelada pelo estabelecimento comercial"),
    Map.entry("0960", "Pagamento/devolução de incentivo comercial sobre o faturamento"),
    Map.entry("0961", "Desconto comercial verba subsidiada pelo banco"),
    Map.entry("0962", "Outros acertos"),
    Map.entry("0963", "Desconto comercial verba subsidiada pelo banco"),
    Map.entry("0964", "Transferência de valores entre estabelecimentos com a mesma raiz CNPJ para compensação de saldo"),
    Map.entry("0965", "Transferência de valores entre estabelecimentos com a mesma raiz CNPJ para compensação de saldo"),
    Map.entry("0966", "Outros acertos"),
    Map.entry("0967", "Cobrança/devolução da taxa de antecipação de recebíveis"),
    Map.entry("0968", "Acerto serviço de recarga"),
    Map.entry("0969", "Cobrança/devolução referente à antecipação do benefício de redução de aluguel"),
    Map.entry("0971", "Pagamento/devolução de comissão periódica"),
    Map.entry("0972", "Crédito/débito referente a processo de \"de/para\" - comercial"),
    Map.entry("0973", "Incentivo serviço Sky"),
    Map.entry("0974", "Tarifa de cadastro Alelo"),
    Map.entry("0975", "Repasse de cobrança do serviço Vivo Easy ao estabelecimento comercial"),
    Map.entry("0976", "Cobrança/devolução da mensalidade do Cielo e-commerce - checkout"),
    Map.entry("0977", "Desconto aluguel"),
    Map.entry("0979", "Incentivo comercial"),
    Map.entry("0981", "Aluguel máquina mobile \"chip and pin\"")
  );

  public static String get(String code) {
    if (code == null) {
      return null;
    }
    return BY_CODE.get(code.trim());
  }
}
