package com.cardsync.domain.model.enums;

public enum ChargebackEventSourceType {
  REQUEST,
  REQUEST_ECOMMERCE,
  PENDING_DEBT,
  PENDING_DEBT_ECOMMERCE,
  SETTLED_DEBT,
  SETTLED_DEBT_ECOMMERCE,
  NET_ADJUSTMENT,
  BANK_DEBIT,
  BANK_DEBIT_ECOMMERCE,
  CREDIT_REVERSAL,
  DESCHEDULEMENT,
  DESCHEDULEMENT_ECOMMERCE,
  ADJUSTMENT,
  CANCELLATION,
  DEBIT_ADJUSTMENT,
  CREDIT_ADJUSTMENT,
  ECOMMERCE_ADJUSTMENT,
  CHARGEBACK_ADJUSTMENT
}
