package com.cardsync.domain.model.enums;

/**
 * Códigos estáveis para UI (server-driven).
 */
public enum PasswordRuleCode {
  PASSWORD_TOO_SHORT,
  PASSWORD_MISSING_LOWER,
  PASSWORD_MISSING_UPPER,
  PASSWORD_MISSING_DIGIT,
  PASSWORD_MISSING_SPECIAL,
  PASSWORD_HAS_WHITESPACE,
  PASSWORD_HAS_SEQUENCE,
  PASSWORD_HAS_REPETITION,
  PASSWORD_COMMON,
  PASSWORD_CONTAINS_USERNAME,
  PASSWORD_NOT_MATCH,
  PASSWORD_REUSED_FROM_HISTORY,
  PASSWORD_SAME_AS_CURRENT
}
