CREATE TABLE cs_adjustment (
  id UUID NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_id UUID NULL,
  updated_by_id UUID NULL,
  nsu BIGINT NULL,
  letter_number BIGINT NULL,
  number_debit_order BIGINT NULL,
  line_number INT NULL,
  rv_number_original INT NULL,
  pv_number_original INT NULL,
  adjustment_status INT NULL,
  adjustment_reason INT NULL,
  adjustment_reason2 INT NULL,
  rv_number_adjustment INT NULL,
  pv_number_adjustment INT NULL,
  rv_number_installment_adjusted INT NULL,
  rv_number_installment_original INT NULL,
  tid VARCHAR(80) NULL,
  net VARCHAR(30) NULL,
  debit_type VARCHAR(30) NULL,
  card_number VARCHAR(80) NULL,
  record_type VARCHAR(20) NULL,
  "authorization" VARCHAR(80) NULL,
  adjustment_type VARCHAR(30) NULL,
  reference_month VARCHAR(20) NULL,
  adjustment_description VARCHAR(255) NULL,
  letter_date DATE NULL,
  credit_date DATE NULL,
  adjustment_date DATE NULL,
  rv_date_adjusted DATE NULL,
  rv_date_original DATE NULL,
  transaction_date DATE NULL,
  pending_value DECIMAL(18,8) NULL,
  total_debit_value DECIMAL(18,8) NULL,
  adjustment_value DECIMAL(18,8) NULL,
  transaction_value DECIMAL(18,8) NULL,
  new_transaction_value DECIMAL(18,8) NULL,
  new_installment_value DECIMAL(18,8) NULL,
  original_value_installment DECIMAL(18,8) NULL,
  cancellation_value_requested DECIMAL(18,8) NULL,
  original_gross_sales_summary_value DECIMAL(18,8) NULL,
  rv_flag_adjustment_id UUID NULL,
  rv_flag_origin_id UUID NULL,
  acquirer_id UUID NULL,
  company_id UUID NULL,
  transaction_id UUID NULL,
  sales_summary_id UUID NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_adjustment_rv_flag_adjustment FOREIGN KEY (rv_flag_adjustment_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_adjustment_rv_flag_origin FOREIGN KEY (rv_flag_origin_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_adjustment_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_adjustment_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_adjustment_transaction FOREIGN KEY (transaction_id) REFERENCES cs_transaction_acq(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_adjustment_sales_summary FOREIGN KEY (sales_summary_id) REFERENCES cs_sales_summary(id) ON UPDATE CASCADE
);
CREATE INDEX idx_cs_adjustment_nsu ON cs_adjustment(nsu);
CREATE INDEX idx_cs_adjustment_rv_adjustment ON cs_adjustment(rv_number_adjustment, pv_number_adjustment);

CREATE TABLE cs_releases_bank (
  id UUID NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_id UUID NULL,
  updated_by_id UUID NULL,
  line_number INT NULL,
  service_lot INT NULL,
  number_parcels INT NULL,
  release_category INT NULL,
  sequential_number INT NULL,
  number_credit_orders INT NULL,
  historical_code_bank INT NULL,
  modality_payment_bank INT NULL,
  release_category_code INT NULL,
  reconciliation_status INT NULL,
  type_complement_release INT NULL,
  company_registration_type INT NULL,
  number_reconciliations INT NULL,
  record_type VARCHAR(20) NULL,
  segment_code VARCHAR(20) NULL,
  release_type VARCHAR(30) NULL,
  nature_release VARCHAR(30) NULL,
  bank_agreement_code VARCHAR(80) NULL,
  complement_release VARCHAR(255) NULL,
  document_complement_number VARCHAR(80) NULL,
  description_historical_bank VARCHAR(255) NULL,
  cpmf_exemption_identification VARCHAR(80) NULL,
  release_value DECIMAL(18,8) NULL,
  release_date DATE NULL,
  accounting_date DATE NULL,
  flag_id UUID NULL,
  bank_id UUID NULL,
  acquirer_id UUID NULL,
  company_id UUID NULL,
  establishment_id UUID NULL,
  processed_file_id UUID NULL,
  banking_domicile_id UUID NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_releases_bank_flag FOREIGN KEY (flag_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_releases_bank_bank FOREIGN KEY (bank_id) REFERENCES cs_bank(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_releases_bank_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_releases_bank_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_releases_bank_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_releases_bank_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_releases_bank_banking_domicile FOREIGN KEY (banking_domicile_id) REFERENCES cs_banking_domicile(id) ON UPDATE CASCADE
);
CREATE INDEX idx_cs_releases_bank_date_value ON cs_releases_bank(release_date, release_value);
CREATE INDEX idx_cs_releases_bank_context ON cs_releases_bank(company_id, acquirer_id, establishment_id, flag_id);

CREATE TABLE cs_credit_order (
  id UUID NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_id UUID NULL,
  updated_by_id UUID NULL,
  credit_order_number BIGINT NULL,
  launch_type VARCHAR(30) NULL,
  record_type VARCHAR(20) NULL,
  rv_number INT NULL,
  line_number INT NULL,
  credit_status INT NULL,
  pv_centralizer INT NULL,
  transaction_type INT NULL,
  original_pv_number INT NULL,
  installment_total INT NULL,
  status_payment_bank INT NULL,
  installment_number INT NULL,
  sales_summary_status INT NULL,
  reconciliation_status INT NULL,
  rv_date DATE NULL,
  release_date DATE NULL,
  credit_order_date DATE NULL,
  release_value DECIMAL(18,8) NULL,
  gross_rv_value DECIMAL(18,8) NULL,
  discount_rate_value DECIMAL(18,8) NULL,
  flag_id UUID NULL,
  acquirer_id UUID NULL,
  company_id UUID NULL,
  processed_file_id UUID NULL,
  sales_summary_id UUID NULL,
  banking_domicile_id UUID NULL,
  release_bank_id UUID NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_credit_order_flag FOREIGN KEY (flag_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_order_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_order_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_order_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_order_sales_summary FOREIGN KEY (sales_summary_id) REFERENCES cs_sales_summary(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_order_banking_domicile FOREIGN KEY (banking_domicile_id) REFERENCES cs_banking_domicile(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_order_release_bank FOREIGN KEY (release_bank_id) REFERENCES cs_releases_bank(id) ON UPDATE CASCADE
);
CREATE INDEX idx_cs_credit_order_rv ON cs_credit_order(rv_number, installment_number, installment_total);
CREATE INDEX idx_cs_credit_order_release ON cs_credit_order(release_date, release_value);
CREATE INDEX idx_cs_credit_order_context ON cs_credit_order(company_id, acquirer_id, flag_id, original_pv_number);

CREATE TABLE cs_installment_acq (
  id UUID NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_id UUID NULL,
  updated_by_id UUID NULL,
  gross_value DECIMAL(18,8) NULL,
  liquid_value DECIMAL(18,8) NULL,
  discount_value DECIMAL(18,8) NULL,
  adjustment_value DECIMAL(18,8) NULL,
  installment INT NULL,
  status_payment_bank INT NULL,
  installment_status INT NULL,
  reconciliation_bank_line INT NULL,
  payment_date DATE NULL,
  cancellation_date DATE NULL,
  expected_payment_date DATE NULL,
  reconciliation_bank_processed_at TIMESTAMP(6) NULL,
  reconciliation_bank_file_id UUID NULL,
  transaction_id UUID NOT NULL,
  credit_order_id UUID NULL,
  release_bank_id UUID NULL,
  adjustment_id UUID NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_installment_acq_reconciliation_file FOREIGN KEY (reconciliation_bank_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_acq_transaction FOREIGN KEY (transaction_id) REFERENCES cs_transaction_acq(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_acq_credit_order FOREIGN KEY (credit_order_id) REFERENCES cs_credit_order(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_acq_release_bank FOREIGN KEY (release_bank_id) REFERENCES cs_releases_bank(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_acq_adjustment FOREIGN KEY (adjustment_id) REFERENCES cs_adjustment(id) ON UPDATE CASCADE
);
CREATE INDEX idx_cs_installment_acq_expected_payment ON cs_installment_acq(expected_payment_date);
CREATE INDEX idx_cs_installment_acq_transaction ON cs_installment_acq(transaction_id);

CREATE TABLE cs_anticipation (
  id UUID NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_id UUID NULL,
  updated_by_id UUID NULL,
  agency INT NULL,
  pv_number INT NULL,
  line_number INT NULL,
  current_account INT NULL,
  number_document INT NULL,
  pv_number_original INT NULL,
  installment_number INT NULL,
  installment_number_max INT NULL,
  number_rv_corresponding INT NULL,
  bank VARCHAR(20) NULL,
  credit VARCHAR(30) NULL,
  record_type VARCHAR(20) NULL,
  release_date DATE NULL,
  original_due_date DATE NULL,
  date_rv_corresponding DATE NULL,
  generated_orders BOOLEAN NULL,
  gross_value DECIMAL(18,8) NULL,
  release_value DECIMAL(18,8) NULL,
  discount_rate_value DECIMAL(18,8) NULL,
  original_credit_value DECIMAL(18,8) NULL,
  flag_id UUID NULL,
  company_id UUID NULL,
  acquirer_id UUID NULL,
  processed_file_id UUID NULL,
  establishment_id UUID NULL,
  sales_summary_id UUID NULL,
  banking_domicile_id UUID NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_anticipation_flag FOREIGN KEY (flag_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_anticipation_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_anticipation_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_anticipation_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_anticipation_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_anticipation_sales_summary FOREIGN KEY (sales_summary_id) REFERENCES cs_sales_summary(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_anticipation_banking_domicile FOREIGN KEY (banking_domicile_id) REFERENCES cs_banking_domicile(id) ON UPDATE CASCADE
);
CREATE INDEX idx_cs_anticipation_pv_release ON cs_anticipation(pv_number, release_date);

CREATE TABLE cs_credit_totalizer (
  id UUID NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_id UUID NULL,
  updated_by_id UUID NULL,
  pv_number INT NULL,
  record_type VARCHAR(20) NULL,
  line_number INT NULL,
  credit_date DATE NULL,
  total_credit_value DECIMAL(18,8) NULL,
  advance_credit_date DATE NULL,
  file_generation_date DATE NULL,
  total_value_advance_credits DECIMAL(18,8) NULL,
  acquirer_id UUID NULL,
  company_id UUID NULL,
  banking_domicile_id UUID NULL,
  processed_file_id UUID NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_credit_totalizer_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_totalizer_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_totalizer_banking_domicile FOREIGN KEY (banking_domicile_id) REFERENCES cs_banking_domicile(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_credit_totalizer_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE
);
CREATE INDEX idx_cs_credit_totalizer_pv_credit_date ON cs_credit_totalizer(pv_number, credit_date);

CREATE TABLE cs_settled_debt (
  id UUID NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_id UUID NULL,
  updated_by_id UUID NULL,
  tid VARCHAR(80) NULL,
  nsu INT NULL,
  pv_number INT NULL,
  record_type VARCHAR(20) NULL,
  card_number VARCHAR(80) NULL,
  line_number INT NULL,
  reason_code INT NULL,
  compensation VARCHAR(255) NULL,
  "authorization" VARCHAR(80) NULL,
  letter_number INT NULL,
  letter_date DATE NULL,
  reference_month VARCHAR(20) NULL,
  reason_description VARCHAR(255) NULL,
  pv_number_original INT NULL,
  number_rv_original INT NULL,
  date_rv_original DATE NULL,
  number_debit_order INT NULL,
  code_compensation INT NULL,
  date_debit_order DATE NULL,
  liquidated_date DATE NULL,
  value_debit_order DECIMAL(18,8) NULL,
  liquidated_value DECIMAL(18,8) NULL,
  number_process_chargeback BIGINT NULL,
  retention_process_number INT NULL,
  date_original_transaction DATE NULL,
  original_transaction_value DECIMAL(18,8) NULL,
  requested_cancellation_value DECIMAL(18,8) NULL,
  code_reason_adjustment2 INT NULL,
  flag_id UUID NULL,
  acquirer_id UUID NULL,
  processed_file_id UUID NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_settled_debt_flag FOREIGN KEY (flag_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_settled_debt_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_settled_debt_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE
);
CREATE INDEX idx_cs_settled_debt_pv_date ON cs_settled_debt(pv_number, liquidated_date);
CREATE INDEX idx_cs_settled_debt_nsu ON cs_settled_debt(nsu);

ALTER TABLE cs_adjustment
  ADD COLUMN ecommerce BOOLEAN NULL,
  ADD COLUMN pv_number INT NULL,
  ADD COLUMN installment_number INT NULL,
  ADD COLUMN installment_total INT NULL,
  ADD COLUMN adjustment_sequence INT NULL,
  ADD COLUMN raw_adjustment_code VARCHAR(80) NULL,
  ADD COLUMN source_record_identifier VARCHAR(20) NULL,
  ADD COLUMN release_date DATE NULL,
  ADD COLUMN original_due_date DATE NULL,
  ADD COLUMN gross_value DECIMAL(18,8) NULL,
  ADD COLUMN liquid_value DECIMAL(18,8) NULL,
  ADD COLUMN discount_value DECIMAL(18,8) NULL,
  ADD COLUMN establishment_id UUID NULL,
  ADD COLUMN processed_file_id UUID NULL;

ALTER TABLE cs_adjustment
  ADD CONSTRAINT fk_cs_adjustment_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  ADD CONSTRAINT fk_cs_adjustment_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE;

CREATE INDEX idx_cs_adjustment_processed_file ON cs_adjustment(processed_file_id);
CREATE INDEX idx_cs_adjustment_record_type ON cs_adjustment(record_type, source_record_identifier);
CREATE INDEX idx_cs_adjustment_context ON cs_adjustment(company_id, acquirer_id, establishment_id, rv_flag_adjustment_id);
CREATE INDEX idx_cs_adjustment_rv_original ON cs_adjustment(rv_number_original, pv_number_original, rv_date_original);

ALTER TABLE cs_adjustment
  ADD COLUMN ecommerce_order_number VARCHAR(80) NULL,
  ADD COLUMN letter_reference VARCHAR(80) NULL;

CREATE INDEX idx_cs_adjustment_ecommerce_order ON cs_adjustment(ecommerce_order_number);
CREATE INDEX idx_cs_adjustment_letter_reference ON cs_adjustment(letter_reference);
