-- Índice funcional duplicado: mesma expressão (LOWER("authorization")) já é criada por
-- idx_acq_authorization_lower em V20260604_01__Add_search_covering_indexes.sql.
-- Mantido como no-op nesta migration para preservar a numeração/histórico do Flyway.
