CREATE TABLE cs_rede_eevd_totalizer (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  record_type VARCHAR(20) NULL,
  line_number INT NULL,
  pv_number INT NULL,
  matrix_number INT NULL,
  sales_summary_quantity INT NULL,
  sales_receipt_quantity INT NULL,
  total_gross_value DECIMAL(18,8) NULL,
  total_discount_value DECIMAL(18,8) NULL,
  total_liquid_value DECIMAL(18,8) NULL,
  predating_gross_value DECIMAL(18,8) NULL,
  predating_discount_value DECIMAL(18,8) NULL,
  predating_liquid_value DECIMAL(18,8) NULL,
  total_file_records INT NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_rede_eevd_totalizer_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_eevd_totalizer_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_eevd_totalizer_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_eevd_totalizer_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_eevd_totalizer_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_eevd_totalizer_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_rede_eevd_totalizer_file_type ON cs_rede_eevd_totalizer(processed_file_id, record_type);
CREATE INDEX idx_cs_rede_eevd_totalizer_pv ON cs_rede_eevd_totalizer(pv_number);

CREATE TABLE cs_rede_negotiated_transaction (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  record_type VARCHAR(20) NULL,
  line_number INT NULL,
  establishment_number INT NULL,
  rv_number INT NULL,
  sale_date DATE NULL,
  rv_credit_date DATE NULL,
  transaction_type VARCHAR(10) NULL,
  flag_code VARCHAR(10) NULL,
  negotiation_type INT NULL,
  settlement_summary_number BIGINT NULL,
  settlement_summary_date DATE NULL,
  settlement_summary_value DECIMAL(18,8) NULL,
  negotiation_contract_number BIGINT NULL,
  partner_cnpj VARCHAR(20) NULL,
  generated_rl_document_number BIGINT NULL,
  negotiated_value DECIMAL(18,8) NULL,
  negotiation_date DATE NULL,
  liquidation_date DATE NULL,
  bank INT NULL,
  agency INT NULL,
  account BIGINT NULL,
  credit_status INT NULL,
  flag_id BINARY(16) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  sales_summary_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_rede_negotiated_flag FOREIGN KEY (flag_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_negotiated_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_negotiated_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_negotiated_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_negotiated_sales_summary FOREIGN KEY (sales_summary_id) REFERENCES cs_sales_summary(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_negotiated_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_negotiated_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_negotiated_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_rede_negotiated_rv ON cs_rede_negotiated_transaction(establishment_number, rv_number);
CREATE INDEX idx_cs_rede_negotiated_file ON cs_rede_negotiated_transaction(processed_file_id);
CREATE INDEX idx_cs_rede_negotiated_liquidation ON cs_rede_negotiated_transaction(liquidation_date);

CREATE TABLE cs_rede_ic_plus_transaction (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  record_type VARCHAR(20) NULL,
  line_number INT NULL,
  pv_number INT NULL,
  rv_number_original INT NULL,
  rv_date_original DATE NULL,
  nsu BIGINT NULL,
  transaction_date DATE NULL,
  mcc INT NULL,
  card_profile VARCHAR(3) NULL,
  interchange_value DECIMAL(18,8) NULL,
  plus_value DECIMAL(18,8) NULL,
  entry_mode VARCHAR(10) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  sales_summary_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_rede_ic_plus_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_ic_plus_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_ic_plus_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_ic_plus_sales_summary FOREIGN KEY (sales_summary_id) REFERENCES cs_sales_summary(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_ic_plus_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_ic_plus_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_rede_ic_plus_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_rede_ic_plus_rv ON cs_rede_ic_plus_transaction(pv_number, rv_number_original);
CREATE INDEX idx_cs_rede_ic_plus_nsu ON cs_rede_ic_plus_transaction(nsu);
CREATE INDEX idx_cs_rede_ic_plus_file ON cs_rede_ic_plus_transaction(processed_file_id);
