INSERT INTO cs_flag (id, status, name, erp_code, text_color, created_at, updated_at, created_by_id) VALUES
	(gen_random_uuid(), '1', 'Mastercard', 1, '#dc2626', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Visa', 2, '#2563eb', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'American Express', 3, '#16a34a', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Diners Club', 4, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Hipercard', 5, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Elo', 6, '#ca8a04', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'PicPay', 7, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'JCB', 8, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Banescard', 9, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Cabal', 10, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Sorocred', 11, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'CUP', 12, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Credsystem (Mais)', 13, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Sicredi', 14, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Avista', 15, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Credz', 16, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Banricompras', 17, '', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Pix', 98, '#2563eb', NOW(), NOW(),NULL),
	(gen_random_uuid(), '1', 'Outras', 99, '#2563eb', NOW(), NOW(),NULL);

INSERT INTO cs_flag_acquirer (id, acquirer_id, flag_id, acquirer_code) VALUES
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Mastercard'), '1'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Diners Club'), '2'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Visa'), '3'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Cabal'), '4'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Hipercard'), '5'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Sorocred'), '6'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'CUP'), '7'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Credsystem (Mais)'),'8'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Sicredi'), '9'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Avista'), 'A'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Elo'), 'E'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Banescard'), 'B'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'JCB'), 'J'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'American Express'), 'X'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Credz'), 'Z'),
	(gen_random_uuid(), (SELECT id FROM cs_acquirer WHERE file_identifier = 'Rede'), (SELECT id FROM cs_flag WHERE name = 'Outras'), '0');
	
INSERT INTO cs_flag_company (id, company_id, flag_id) VALUES
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Mastercard')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Diners Club')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Visa')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Cabal')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Hipercard')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Sorocred')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'CUP')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Credsystem (Mais)')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Sicredi')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Banescard')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Elo')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'JCB')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'American Express')),
    (gen_random_uuid(), (SELECT id FROM cs_company WHERE cnpj = '39303847000180'), (SELECT id FROM cs_flag WHERE name = 'Credz'));