CREATE TABLE cs_pv_matrix_header (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  pv_number INT NULL,
  line_number INT NULL,
  record_type VARCHAR(20) NULL,
  commercial_name VARCHAR(120) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_pv_matrix_header_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pv_matrix_header_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pv_matrix_header_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pv_matrix_header_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pv_matrix_header_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pv_matrix_header_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_pv_matrix_header_pv ON cs_pv_matrix_header(pv_number);

CREATE TABLE cs_serasa_consultation (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  pv_number INT NULL,
  line_number INT NULL,
  record_type VARCHAR(20) NULL,
  number_consultation_carried_out INT NULL,
  total_value_consultation DECIMAL(18,8) NULL,
  start_consultation_period DATE NULL,
  end_consultation_period DATE NULL,
  value_consultation_period DECIMAL(18,8) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_serasa_consultation_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_serasa_consultation_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_serasa_consultation_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_serasa_consultation_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_serasa_consultation_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_serasa_consultation_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_serasa_consultation_pv_period ON cs_serasa_consultation(pv_number, start_consultation_period, end_consultation_period);

CREATE TABLE cs_pending_debt (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  tid VARCHAR(80) NULL,
  nsu BIGINT NULL,
  pv_number INT NULL,
  record_type VARCHAR(20) NULL,
  card_number VARCHAR(80) NULL,
  line_number INT NULL,
  reason_code INT NULL,
  authorization VARCHAR(80) NULL,
  letter_number BIGINT NULL,
  letter_date DATE NULL,
  reference_month VARCHAR(20) NULL,
  reason_description VARCHAR(255) NULL,
  pv_number_original INT NULL,
  number_rv_original INT NULL,
  date_rv_original DATE NULL,
  number_debit_order BIGINT NULL,
  date_debit_order DATE NULL,
  value_debit_order DECIMAL(18,8) NULL,
  compensated_value DECIMAL(18,8) NULL,
  number_process_chargeback BIGINT NULL,
  date_original_transaction DATE NULL,
  original_transaction_value DECIMAL(18,8) NULL,
  flag_id BINARY(16) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_pending_debt_flag FOREIGN KEY (flag_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pending_debt_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pending_debt_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pending_debt_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pending_debt_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pending_debt_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_pending_debt_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_pending_debt_pv_date ON cs_pending_debt(pv_number, date_debit_order);
CREATE INDEX idx_cs_pending_debt_nsu ON cs_pending_debt(nsu);

CREATE TABLE cs_installment_unscheduling (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  nsu BIGINT NULL,
  tid VARCHAR(80) NULL,
  order_number VARCHAR(80) NULL,
  record_type VARCHAR(20) NULL,
  card_number VARCHAR(80) NULL,
  type_debit VARCHAR(30) NULL,
  line_number INT NULL,
  number_installment INT NULL,
  pv_number_original INT NULL,
  rv_number_original INT NULL,
  unscheduling_status INT NULL,
  reference_number VARCHAR(80) NULL,
  ecommerce BIT NULL,
  date_credit DATE NULL,
  cancellation_date DATE NULL,
  transaction_date DATE NULL,
  rv_value_original DECIMAL(18,8) NULL,
  adjustment_value DECIMAL(18,8) NULL,
  cancellation_value DECIMAL(18,8) NULL,
  new_installment_value DECIMAL(18,8) NULL,
  original_value_changed_installment DECIMAL(18,8) NULL,
  flag_rv_origin_id BINARY(16) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_installment_unscheduling_flag FOREIGN KEY (flag_rv_origin_id) REFERENCES cs_flag(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_unscheduling_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_unscheduling_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_unscheduling_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_unscheduling_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_unscheduling_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_installment_unscheduling_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_installment_unscheduling_rv ON cs_installment_unscheduling(pv_number_original, rv_number_original);
CREATE INDEX idx_cs_installment_unscheduling_nsu ON cs_installment_unscheduling(nsu);

CREATE TABLE cs_totalizer_matrix (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  pv_number INT NULL,
  line_number INT NULL,
  record_type VARCHAR(20) NULL,
  total_number_matrix_summaries INT NULL,
  total_value_normal_credits DECIMAL(18,8) NULL,
  value_advance_credits INT NULL,
  total_value_anticipated DECIMAL(18,8) NULL,
  amount_credit_adjustments INT NULL,
  total_value_credit_adjustments DECIMAL(18,8) NULL,
  amount_debit_adjustments INT NULL,
  total_value_debit_adjustments DECIMAL(18,8) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_totalizer_matrix_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_totalizer_matrix_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_totalizer_matrix_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_totalizer_matrix_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_totalizer_matrix_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_totalizer_matrix_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_totalizer_matrix_pv ON cs_totalizer_matrix(pv_number);

CREATE TABLE cs_archive_trailer (
  id BINARY(16) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  created_by_id BINARY(16) NULL,
  updated_by_id BINARY(16) NULL,
  line_number INT NULL,
  record_type VARCHAR(20) NULL,
  number_matrices INT NULL,
  number_records INT NULL,
  pv_requesting INT NULL,
  normal_credits_quantity INT NULL,
  total_value_rv DECIMAL(18,8) NULL,
  advance_credit_amount INT NULL,
  total_value_upfront DECIMAL(18,8) NULL,
  amount_credit_adjustments INT NULL,
  total_value_credit_adjustments DECIMAL(18,8) NULL,
  debit_adjustment_quantity INT NULL,
  total_value_debit DECIMAL(18,8) NULL,
  acquirer_id BINARY(16) NULL,
  company_id BINARY(16) NULL,
  establishment_id BINARY(16) NULL,
  processed_file_id BINARY(16) NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cs_archive_trailer_acquirer FOREIGN KEY (acquirer_id) REFERENCES cs_acquirer(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_archive_trailer_company FOREIGN KEY (company_id) REFERENCES cs_company(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_archive_trailer_establishment FOREIGN KEY (establishment_id) REFERENCES cs_establishment(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_archive_trailer_processed_file FOREIGN KEY (processed_file_id) REFERENCES cs_processed_file(id) ON UPDATE CASCADE,
  CONSTRAINT fk_cs_archive_trailer_created_by FOREIGN KEY (created_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_archive_trailer_updated_by FOREIGN KEY (updated_by_id) REFERENCES cs_users(id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;
CREATE INDEX idx_cs_archive_trailer_file ON cs_archive_trailer(processed_file_id);
