INSERT INTO cs_contracts(id, status, start_date, end_date, description, company_id, acquirer_id, establishment_id) VALUES
    (UUID_TO_BIN(UUID()), 1,'2025-01-01','2025-12-31','Acquamania - Rede S/A - 7867379',
      (SELECT id FROM cs_company WHERE cnpj = '39303847000180'),
      (SELECT id FROM cs_acquirer WHERE cnpj = '01425787000104'),
      (SELECT id FROM cs_establishment WHERE pv_number = '7867379'));

INSERT INTO cs_contract_flags(id, flag_id, contract_id) VALUES
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Mastercard'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Visa'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'American Express'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Diners Club'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Hipercard'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Elo'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'PicPay'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Banescard'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Cabal'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Sorocred'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'CUP'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Credsystem (Mais)'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Sicredi'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379')),
    (UUID_TO_BIN(UUID()), (SELECT id FROM cs_flag WHERE name = 'Avista'),
      (SELECT id FROM cs_contracts WHERE description = 'Acquamania - Rede S/A - 7867379'));
